deployment:
  tasks:
    - export DEPLOYPATH=/home/arplus/vpick

    # Đồng bộ code mới, bỏ qua storage và .env
    - /bin/rsync -av --delete --exclude 'storage/' --exclude '.env' ./ $DEPLOYPATH

    # Clear cache Laravel (nếu có dùng cache)
    - cd $DEPLOYPATH && /bin/php artisan config:clear
    - cd $DEPLOYPATH && /bin/php artisan cache:clear
    - cd $DEPLOYPATH && /bin/php artisan route:clear
    - cd $DEPLOYPATH && /bin/php artisan view:clear
